---
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql
spec:
  images:
    - major: 15
      image: ghcr.io/cloudnative-pg/postgresql:15.13
    - major: 16
      image: ghcr.io/cloudnative-pg/postgresql:16.9
    - major: 17
      image: ghcr.io/cloudnative-pg/postgresql:17.5