---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  annotations:
    kubernetes.io/description: "CloudNative-PG is a Kubernetes operator for PostgreSQL with native high availability and automated failover"
spec:
  interval: 20m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.24.0
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
  values:
    namespaceOverride: cnpg-system

    # Enable monitoring and metrics
    monitoring:
      enabled: true
      podMonitorEnabled: true
      podMonitor:
        enabled: true

    # Enable metrics collection
    config:
      data:
        MONITORING_ENABLED: "true"

    # Additional RBAC permissions for advanced features
    rbac:
      create: true
      rules:
        # Standard permissions (included by default)
        - apiGroups: [""]
          resources: ["events"]
          verbs: ["create", "patch"]
        - apiGroups: [""]
          resources: ["configmaps"]
          verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
        - apiGroups: [""]
          resources: ["secrets"]
          verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
        - apiGroups: [""]
          resources: ["pods"]
          verbs: ["get", "list", "watch", "delete"]
        - apiGroups: [""]
          resources: ["pods/exec"]
          verbs: ["get", "list", "create"]
        - apiGroups: [""]
          resources: ["services"]
          verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
        - apiGroups: [""]
          resources: ["persistentvolumeclaims"]
          verbs: ["get", "list", "create", "update", "patch", "delete"]
        - apiGroups: [""]
          resources: ["jobs"]
          verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
        - apiGroups: ["batch"]
          resources: ["jobs"]
          verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
        - apiGroups: ["apps"]
          resources: ["deployments"]
          verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
        - apiGroups: ["policy"]
          resources: ["poddisruptionbudgets"]
          verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
        - apiGroups: ["postgresql.cnpg.io"]
          resources: ["backups", "clusters", "poolers", "scheduledbackups", "clusterrolebindings"]
          verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
        - apiGroups: ["postgresql.cnpg.io"]
          resources: ["backups/status", "clusters/status", "poolers/status", "scheduledbackups/status", "clusterrolebindings/status"]
          verbs: ["get", "patch", "update", "watch"]
        # Additional permissions for failoverquorums
        - apiGroups: ["postgresql.cnpg.io"]
          resources: ["failoverquorums"]
          verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
        - apiGroups: ["postgresql.cnpg.io"]
          resources: ["failoverquorums/status"]
          verbs: ["get", "patch", "update", "watch"]
