---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
spec:
  interval: 20m
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.24.0
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
  values:
    namespaceOverride: cnpg-system

    # Enable monitoring and metrics
    monitoring:
      enabled: true
      podMonitorEnabled: true
      podMonitor:
        enabled: true

    # Enable metrics collection
    config:
      data:
        MONITORING_ENABLED: "true"
