---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
spec:
  replicas: 1
  serviceName: mariadb
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.11 # {"$imagepolicy": "mariadb:mariadb"}
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: mariadb
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb
        - name: exporter
          image: prom/mysqld-exporter:v0.16.0 # {"$imagepolicy": "mariadb:mysqld-exporter"}
          imagePullPolicy: "IfNotPresent"
          args:
            - --config.my-cnf=/conf/my.cnf
          ports:
            - containerPort: 9104
          volumeMounts:
            - mountPath: /conf
              name: exporter
      volumes:
        - name: mariadb
          persistentVolumeClaim:
            claimName: mariadb-data
        - name: exporter
          secret:
            secretName: exporter
