# Standard Service Account Template
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: SERVICE_ACCOUNT_NAME
  namespace: NAMESPACE_NAME
  annotations:
    # Add annotations as needed
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: NAMESPACE_NAME
  name: SERVICE_ACCOUNT_NAME-role
rules:
# Add rules as needed for the service account
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: SERVICE_ACCOUNT_NAME-binding
  namespace: NAMESPACE_NAME
subjects:
- kind: ServiceAccount
  name: SERVICE_ACCOUNT_NAME
  namespace: NAMESPACE_NAME
roleRef:
  kind: Role
  name: SERVICE_ACCOUNT_NAME-role
  apiGroup: rbac.authorization.k8s.io