---
apiVersion: v1
kind: Service
metadata:
  name: valkey
  labels:
    app: valkey
spec:
  type: ClusterIP
  ports:
  - port: 6379
    name: valkey
  selector:
    app: valkey

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: valkey
data:
  valkey.conf: |
    # Valkey configuration
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    save ""
    appendonly no
    protected-mode yes
    bind 0.0.0.0
    dir /tmp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      securityContext:
        fsGroup: 999
        runAsUser: 999
        runAsNonRoot: true
      containers:
      - name: valkey
        image: valkey/valkey:7-alpine
        command:
        - valkey-server
        args:
        - /etc/valkey/valkey.conf
        ports:
        - containerPort: 6379
          name: valkey
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - valkey-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - valkey-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: config
          mountPath: "/etc/valkey"
          readOnly: true
      volumes:
        - name: config
          configMap:
            name: valkey
            items:
            - key: "valkey.conf"
              path: "valkey.conf"
