---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
spec:
  interval: 20m
  chart:
    spec:
      chart: grafana
      version: 9.2.2
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
