# Database Monitoring Alert Rules Template
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: database-monitoring-alerts
  labels:
    app: prometheus
    team: platform
spec:
  groups:
    - name: postgresql.rules
      rules:
        - alert: PostgreSQLDown
          expr: pg_up == 0
          for: 5m
          labels:
            severity: critical
            team: platform
          annotations:
            summary: "PostgreSQL is down"
            description: "PostgreSQL instance {{ $labels.instance }} is down for more than 5 minutes."

        - alert: PostgreSQLHighConnections
          expr: |
            (
              pg_stat_database_numbackends / pg_settings_max_connections * 100 > 80
            )
          for: 10m
          labels:
            severity: warning
            team: platform
          annotations:
            summary: "PostgreSQL high connection usage"
            description: "PostgreSQL instance {{ $labels.instance }} is using {{ printf \"%.2f\" $value }}% of available connections."

        - alert: PostgreSQLSlowQueries
          expr: |
            (
              avg_over_time(pg_stat_activity_max_tx_duration[5m]) > 300
            )
          for: 10m
          labels:
            severity: warning
            team: platform
          annotations:
            summary: "PostgreSQL slow queries detected"
            description: "PostgreSQL instance {{ $labels.instance }} has queries running longer than 5 minutes."

        - alert: PostgreSQLReplicationLag
          expr: |
            (
              pg_stat_replication_lag > 60
            )
          for: 5m
          labels:
            severity: warning
            team: platform
          annotations:
            summary: "PostgreSQL replication lag"
            description: "PostgreSQL replication lag is {{ humanizeDuration $value }} on {{ $labels.instance }}."

    - name: cnpg.rules
      rules:
        - alert: CNPGClusterDegraded
          expr: cnpg_collector_pg_cluster_status != 1
          for: 5m
          labels:
            severity: critical
            team: platform
          annotations:
            summary: "CNPG cluster degraded"
            description: "CNPG cluster {{ $labels.cluster }} in namespace {{ $labels.namespace }} is in a degraded state."

        - alert: CNPGInstanceDown
          expr: cnpg_collector_pg_cluster_instances_ready < cnpg_collector_pg_cluster_instances
          for: 10m
          labels:
            severity: warning
            team: platform
          annotations:
            summary: "CNPG instance down"
            description: "CNPG cluster {{ $labels.cluster }} in namespace {{ $labels.namespace }} has {{ $value }} instances down."

        - alert: CNPGSwitchoverEvent
          expr: increase(cnpg_collector_pg_cluster_switchover_required[5m]) > 0
          for: 0m
          labels:
            severity: info
            team: platform
          annotations:
            summary: "CNPG switchover required"
            description: "CNPG cluster {{ $labels.cluster }} in namespace {{ $labels.namespace }} requires a switchover."

        - alert: CNPGBackupFailed
          expr: |
            (
              time() - on(cluster) cnpg_collector_pg_cluster_backup_last_backup_timestamp > 86400
            )
          for: 1h
          labels:
            severity: critical
            team: platform
          annotations:
            summary: "CNPG backup failed"
            description: "CNPG cluster {{ $labels.cluster }} in namespace {{ $labels.namespace }} has not completed a backup in the last 24 hours."

    - name: redis.rules
      rules:
        - alert: RedisDown
          expr: redis_up == 0
          for: 5m
          labels:
            severity: critical
            team: platform
          annotations:
            summary: "Redis is down"
            description: "Redis instance {{ $labels.instance }} is down for more than 5 minutes."

        - alert: RedisHighMemoryUsage
          expr: |
            (
              redis_memory_used_bytes / redis_memory_max_bytes * 100 > 80
            )
          for: 10m
          labels:
            severity: warning
            team: platform
          annotations:
            summary: "Redis high memory usage"
            description: "Redis instance {{ $labels.instance }} is using {{ printf \"%.2f\" $value }}% of available memory."

        - alert: RedisConnectionsHigh
          expr: |
            (
              redis_connected_clients / redis_config_maxclients * 100 > 80
            )
          for: 10m
          labels:
            severity: warning
            team: platform
          annotations:
            summary: "Redis high connection usage"
            description: "Redis instance {{ $labels.instance }} is using {{ printf \"%.2f\" $value }}% of available connections."

        - alert: RedisSlowLog
          expr: increase(redis_slowlog_length[5m]) > 0
          for: 5m
          labels:
            severity: warning
            team: platform
          annotations:
            summary: "Redis slow commands detected"
            description: "Redis instance {{ $labels.instance }} has {{ $value }} slow commands in the last 5 minutes."

    - name: mariadb.rules
      rules:
        - alert: MariaDBDown
          expr: mysql_up == 0
          for: 5m
          labels:
            severity: critical
            team: platform
          annotations:
            summary: "MariaDB is down"
            description: "MariaDB instance {{ $labels.instance }} is down for more than 5 minutes."

        - alert: MariaDBHighConnections
          expr: |
            (
              mysql_global_status_threads_connected / mysql_global_variables_max_connections * 100 > 80
            )
          for: 10m
          labels:
            severity: warning
            team: platform
          annotations:
            summary: "MariaDB high connection usage"
            description: "MariaDB instance {{ $labels.instance }} is using {{ printf \"%.2f\" $value }}% of available connections."

        - alert: MariaDBSlowQueries
          expr: increase(mysql_global_status_slow_queries[5m]) > 0
          for: 10m
          labels:
            severity: warning
            team: platform
          annotations:
            summary: "MariaDB slow queries detected"
            description: "MariaDB instance {{ $labels.instance }} has {{ $value }} slow queries in the last 5 minutes."

        - alert: MariaDBReplicationLag
          expr: |
            (
              mysql_slave_seconds_behind_master > 60
            )
          for: 5m
          labels:
            severity: warning
            team: platform
          annotations:
            summary: "MariaDB replication lag"
            description: "MariaDB replication lag is {{ humanizeDuration $value }} on {{ $labels.instance }}."
