# DNS Monitoring Alert Rules Template
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: dns-rules
  labels:
    app: prometheus
spec:
  groups:
    - name: dns.rules
      rules:
        - alert: DNSQueryFailed
          expr: probe_success{job="BlackboxDNSMetrics"} == 0
          for: 5m
          labels:
            team: infra
            service: dns
            severity: critical
          annotations:
            summary: "DNS query to {{ $labels.instance }} failed"
            description: "DNS probe to {{ $labels.instance }} for {{ $labels.domain }} has failed for 5 minutes."
        - alert: DNSHighLatency
          expr: probe_duration_seconds{job="BlackboxDNSMetrics"} > 0.5
          for: 2m
          labels:
            team: infra
            service: dns
            severity: warning
          annotations:
            summary: "High DNS latency for {{ $labels.instance }}"
            description: "DNS query latency to {{ $labels.instance }} exceeds 0.5s for 2 minutes."
