---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argo-workflows
  annotations:
    kubernetes.io/description: "Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes"
spec:
  interval: 20m
  chart:
    spec:
      chart: argo-workflows
      version: 0.45.14
      sourceRef:
        kind: HelmRepository
        name: argoproj
        namespace: flux-system
  values:
    controller:
      logging:
        format: json
      workflowNamespaces:
        - kube-system  # Override this in cluster-specific configurations
      metricsConfig:
        enabled: true
      extraEnv:
        - name: WATCH_CONTROLLER_SEMAPHORE_CONFIGMAPS
          value: "false"
    server:
      extraArgs:
        - --auth-mode=client
    workflow:
      serviceAccount:
        create: true
        name: "argo-workflow"
      rbac:
        create: true
