---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  annotations:
    kubernetes.io/description: "Secrets management and data protection platform with encryption services"
spec:
  interval: 20m
  chart:
    spec:
      chart: vault
      version: 0.29.1
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  values:
    global:
      psp:
        enable: false

    injector:
      enabled: false

    server:
      dataStorage:
        enabled: false

      ingress:
        enabled: false

    ui:
      enabled: true
