---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres-operator
  annotations:
    kubernetes.io/description: "PostgreSQL operator for managing PostgreSQL clusters on Kubernetes"
spec:
  interval: 18m
  chart:
    spec:
      chart: postgres-operator
      version: 1.12.2
      sourceRef:
        kind: HelmRepository
        name: postgres-operator
        namespace: flux-system
  values: {}