---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  annotations:
    kubernetes.io/description: "Kubernetes metrics API for CPU and memory usage data"
spec:
  interval: 20m
  chart:
    spec:
      chart: metrics-server
      version: "3.8.2"
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
  values:
    args:
      - --kubelet-insecure-tls
