apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dragonfly-mysql
  namespace: dragonfly-system
spec:
  serviceName: dragonfly-mysql
  replicas: 1
  selector:
    matchLabels:
      app: dragonfly-mysql
  template:
    metadata:
      labels:
        app: dragonfly-mysql
    spec:
      # Prefer healthy worker nodes
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - "acme-operations-workernode-5"
                - "acme-operations-workernode-1"
      # Security context for pod (Kyverno policy compliance)
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      # Image pull secrets for private registry
      imagePullSecrets:
        - name: harbor-credentials
      containers:
      - name: mysql
        image: harbor.golder.lan/dockerhub/library/mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql
        # Security context for container (Kyverno policy compliance)
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        env:
        - name: MYSQL_DATABASE
          value: "dragonfly"
        - name: MYSQL_USER
          value: "dragonfly"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dragonfly-config
              key: mysql-root-password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dragonfly-config
              key: mysql-password
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        # Health probes for Kyverno policy compliance
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - mysqladmin ping -h localhost -u root -p$MYSQL_ROOT_PASSWORD
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - mysql -h localhost -u root -p$MYSQL_ROOT_PASSWORD -e "SELECT 1"
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: csi-driver-lvm-linear
      resources:
        requests:
          storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: dragonfly-mysql
  namespace: dragonfly-system
spec:
  selector:
    app: dragonfly-mysql
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  type: ClusterIP
