apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dragonfly-system
resources:
  - namespace.yaml
  - dragonfly-db.yaml
  - valkey.yaml
  - dragonfly.yaml
  - proxy-service.yaml
  - servicemonitor.yaml
