---
apiVersion: v1
kind: Service
metadata:
  name: valkey
  labels:
    app: valkey
spec:
  type: ClusterIP
  ports:
  - port: 6379
    name: valkey
  selector:
    app: valkey

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: valkey
data:
  valkey.conf: |
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    save "900 1"
    appendonly yes
    protected-mode yes
    bind 0.0.0.0
    dir /data

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: valkey
spec:
  serviceName: "valkey"
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      # Security context for pod (Kyverno policy compliance)
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: valkey
        image: docker.io/valkey/valkey:7.2.7-alpine
        ports:
        - containerPort: 6379
          name: valkey
        # Security context for container (Kyverno policy compliance)
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        volumeMounts:
        - name: config
          mountPath: "/etc/valkey"
          readOnly: true
        - name: valkey-data
          mountPath: /data
        env:
        - name: VALKEY_AUTH
          valueFrom:
            secretKeyRef:
              name: dragonfly-config  # pragma: allowlist secret
              key: valkey-password  # pragma: allowlist secret
        command:
        - sh
        - -c
        - |
          echo "requirepass $VALKEY_AUTH" >> /tmp/valkey.conf
          cat /etc/valkey/valkey.conf >> /tmp/valkey.conf
          valkey-server /tmp/valkey.conf
        # Health probes for Kyverno policy compliance
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              valkey-cli -a "$VALKEY_AUTH" ping
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - |
              valkey-cli -a "$VALKEY_AUTH" ping
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
        - name: config
          configMap:
            name: valkey
            items:
            - key: "valkey.conf"
              path: "valkey.conf"
  volumeClaimTemplates:
  - metadata:
      name: valkey-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: csi-driver-lvm-linear
      resources:
        requests:
          storage: 2Gi
