---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
spec:
  interval: 20m
  chart:
    spec:
      chart: kyverno
      version: 3.2.6
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: flux-system
  values:
    admissionController:
      replicas: 2
      resources:
        limits:
          memory: 384Mi
        requests:
          cpu: 100m
          memory: 128Mi
    backgroundController:
      resources:
        limits:
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 64Mi
    cleanupController:
      resources:
        limits:
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 64Mi
    reportsController:
      resources:
        limits:
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 64Mi