---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  annotations:
    kubernetes.io/description: "External Secrets Operator reads secrets from external systems and creates Kubernetes secrets"
spec:
  interval: 20m
  chart:
    spec:
      chart: external-secrets
      version: v0.18.2
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  values:
    installCRDs: true
