---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: fluent-operator
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: fluent
        namespace: flux-system
      interval: 5m
  values:
    fluentbit:
      serviceMonitor:
        enable: false