---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blackboxexporter
  annotations:
    kubernetes.io/description: "Prometheus blackbox exporter for probing HTTP, HTTPS, DNS, TCP and ICMP endpoints"
spec:
  interval: 18m
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      version: 9.0.0
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
  values: {}
