---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pingexporter
spec:
  interval: 18m
  chart:
    spec:
      chart: ping-exporter
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: czerwonk
        namespace: flux-system

  values: {}
