---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
spec:
  interval: 18m
  chart:
    spec:
      chart: prometheus
      version: 26.0.0
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system

  values: {}
