---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snmpexporter
spec:
  interval: 18m
  chart:
    spec:
      chart: prometheus-snmp-exporter
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system
  values: {}
