---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubescape-operator
spec:
  interval: 20m
  chart:
    spec:
      chart: kubescape-operator
      version: 1.16.5
      sourceRef:
        kind: HelmRepository
        name: kubescape
        namespace: flux-system
  values:
    capabilities:
      relevancy: enable
      configurationScan: enable
      continuousScan: disable
      vulnerabilityScan: enable
      nodeScan: enable
    operator:
      image:
        tag: "v1.0.55"
    gateway:
      image:
        tag: "v1.0.55"