---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubescape-operator
  annotations:
    kubernetes.io/description: "Kubescape provides comprehensive Kubernetes security posture management with vulnerability scanning and compliance checks"
spec:
  interval: 18m
  chart:
    spec:
      chart: kubescape-operator
      version: 1.16.5
      sourceRef:
        kind: HelmRepository
        name: kubescape
        namespace: flux-system
  values:
    global:
      clusterName: "CLUSTER_NAME_PLACEHOLDER"
    capabilities:
      relevancy: enable
      configurationScan: enable
      continuousScan: disable
      vulnerabilityScan: enable
      nodeScan: disable

    # Completely disable nodeAgent to avoid host access violations
    nodeAgent:
      enabled: false

    # Security hardening for Kyverno policy compliance
    operator:
      image:
        tag: "v3.0.19"  # Explicit tag instead of latest
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
      serviceAccount:
        automountServiceAccountToken: false

    kubescape:
      image:
        tag: "v3.0.19"  # Explicit tag instead of latest
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
      serviceAccount:
        automountServiceAccountToken: false

    kollector:
      image:
        tag: "v1.24.17"  # Explicit tag instead of latest
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - ALL
      serviceAccount:
        automountServiceAccountToken: false
