---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csi-driver-lvm
  namespace: flux-system
spec:
  interval: 18m
  path: ./infrastructure/csi-driver-lvm
  prune: true
  sourceRef:
    kind: GitRepository
    name: FLUX_REPO_NAME
