---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-lvm
spec:
  interval: 18m
  timeout: 5m
  chart:
    spec:
      chart: csi-driver-lvm
      version: "0.9.0"
      sourceRef:
        kind: HelmRepository
        name: metal-stack
        namespace: flux-system
  values:
    storageClass:
      create: true
      name: csi-driver-lvm-linear
      reclaimPolicy: Delete
      volumeBindingMode: WaitForFirstConsumer
