---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-lvm
spec:
  interval: 20m
  chart:
    spec:
      chart: csi-driver-lvm
      version: 0.7.0
      sourceRef:
        kind: HelmRepository
        name: metalstack
        namespace: flux-system