---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
  annotations:
    kubernetes.io/description: "Self-hosted Git service with web interface"
spec:
  interval: 20m
  chartRef:
    kind: OCIRepository
    name: gitea
    namespace: flux-system
