---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    name: redis
  selector:
    app: redis

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis
data:
  redis.conf: |
    maxmemory 16mb
    maxmemory-policy allkeys-lru
    # Password configuration should be added via cluster-specific patches
    # Example: requirepass ${REDIS_PASSWORD}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: "redis"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        command:
        - redis-server
        args:
        - /etc/redis/redis.conf
        ports:
        - containerPort: 6379
          name: web
        volumeMounts:
        - name: config
          mountPath: "/etc/redis"
          readOnly: true
      volumes:
        - name: config
          configMap:
            name: redis
            items:
            - key: "redis.conf"
              path: "redis.conf"
