---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cilium-network-policies
  annotations:
    policies.kyverno.io/title: "Cilium Network Policies"
    policies.kyverno.io/category: "Network Security"
    policies.kyverno.io/severity: "medium"
    policies.kyverno.io/description: >-
      Automatically generates default-deny Cilium network policies for new
      namespaces and recommends egress rules for better security. Ensures
      proper network segmentation with Cilium's eBPF-based enforcement.
spec:
  admission: true
  background: true
  emitWarning: false            # Can be overridden per cluster
  validationFailureAction: Audit  # AUDIT MODE ONLY
  rules:
    # Require Cilium network policies for new namespaces
    - name: require-cilium-policies
      match:
        any:
        - resources:
            kinds:
            - Namespace
      exclude:
        resources:
          names:
          - default
          - kube-system
          - kube-public
          - kube-node-lease
          - vault                   # Vault has custom network requirements
          - haproxy-system          # HAProxy needs broad egress access
          - external-secrets        # May need broad egress access
          - fluent-operator         # May need broad egress access
      skipBackgroundRequests: true
      generate:
        apiVersion: cilium.io/v2
        kind: CiliumNetworkPolicy
        name: default-deny-ingress
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        data:
          metadata:
            annotations:
              kubernetes.io/description: "Auto-generated default deny ingress policy"
          spec:
            description: "Default deny all ingress traffic"
            endpointSelector: {}
            ingress:
            - fromEndpoints:
              - matchLabels:
                  k8s:io.kubernetes.pod.namespace: "{{request.object.metadata.name}}"

    # Recommend egress policies
    - name: check-egress-policies
      match:
        any:
        - resources:
            kinds:
            - CiliumNetworkPolicy
      skipBackgroundRequests: true
      validate:
        allowExistingViolations: true
        message: "Consider defining egress rules for better security"
        pattern:
          spec:
            =(egress):
            - "?*"
