---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium-rbac.yaml
  - cilium-policies.yaml
  - cnpg-exception.yaml
  - container-security-standards-override.yaml
  - crossplane-providers-enhanced-exception.yaml
  - crossplane-providers-exception.yaml
  - external-secrets-exception.yaml
  - flux-multi-tenancy-fixed.yaml
  # - flux-multi-tenancy.yaml  # Commented out - using flux-multi-tenancy-fixed.yaml instead
  - gitea-exception.yaml
  - gitops-policies.yaml
  - keycloak-exception.yaml
  - kyverno-exception.yaml
  - prevent-hardcoded-secrets.yaml
  - rbac-policies.yaml
  - registry-policies.yaml
  - security-policies.yaml
  - storage-policies.yaml