---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: allowed-image-registries
  annotations:
    policies.kyverno.io/title: "Allowed Image Registries"
    policies.kyverno.io/category: "Supply Chain Security"
    policies.kyverno.io/severity: "high"
    policies.kyverno.io/description: >-
      Restricts container images to approved registries only: harbor.golder.lan
      (internal), specific ghcr.io namespaces (cloudnative-pg, codecentric, external-secrets,
      fluent, fluxcd, grafana, kubeshop, kyverno, linkchecker, metal-stack, netbox-community),
      vaultwarden/*, hashicorp, goharbor, docker.gitea.com, docker.io/dragonflyoss/*, 
      and registry.k8s.io to prevent use of untrusted image sources.
spec:
  validationFailureAction: enforce
  background: true
  rules:
    - name: validate-registries
      match:
        any:
        - resources:
            kinds:
            - Pod
            - Deployment
            - StatefulSet
            - DaemonSet
            - Job
            - CronJob
      validate:
        message: "Images must be pulled from approved registries"
        pattern:
          spec:
            containers:
            - image: "harbor.golder.lan/* | ghcr.io/cloudnative-pg/* | ghcr.io/codecentric/* | ghcr.io/external-secrets/* | ghcr.io/fluent/* | ghcr.io/fluxcd/* | ghcr.io/grafana/* | ghcr.io/kubeshop/* | ghcr.io/kyverno/* | ghcr.io/linkchecker/* | ghcr.io/metal-stack/* | ghcr.io/netbox-community/* | vaultwarden/* | hashicorp/* | goharbor/* | docker.gitea.com/* | docker.io/dragonflyoss/* | registry.k8s.io/* | xpkg.upbound.io/* | xpkg.crossplane.io/* | oci.external-secrets.io/*"
            =(initContainers):
            - image: "harbor.golder.lan/* | ghcr.io/cloudnative-pg/* | ghcr.io/codecentric/* | ghcr.io/external-secrets/* | ghcr.io/fluent/* | ghcr.io/fluxcd/* | ghcr.io/grafana/* | ghcr.io/kubeshop/* | ghcr.io/kyverno/* | ghcr.io/linkchecker/* | ghcr.io/metal-stack/* | ghcr.io/netbox-community/* | vaultwarden/* | hashicorp/* | goharbor/* | docker.gitea.com/* | docker.io/dragonflyoss/* | registry.k8s.io/* | xpkg.upbound.io/* | xpkg.crossplane.io/* | oci.external-secrets.io/*"
            =(ephemeralContainers):
            - image: "harbor.golder.lan/* | ghcr.io/cloudnative-pg/* | ghcr.io/codecentric/* | ghcr.io/external-secrets/* | ghcr.io/fluent/* | ghcr.io/fluxcd/* | ghcr.io/grafana/* | ghcr.io/kubeshop/* | ghcr.io/kyverno/* | ghcr.io/linkchecker/* | ghcr.io/metal-stack/* | ghcr.io/netbox-community/* | vaultwarden/* | hashicorp/* | goharbor/* | docker.gitea.com/* | docker.io/dragonflyoss/* | registry.k8s.io/* | xpkg.upbound.io/* | xpkg.crossplane.io/* | oci.external-secrets.io/*"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-image-pull-secrets
  annotations:
    policies.kyverno.io/title: "Require Image Pull Secrets"
    policies.kyverno.io/category: "Supply Chain Security"
    policies.kyverno.io/severity: "low"
    policies.kyverno.io/description: >-
      Ensures that images from private registries (harbor.golder.lan) use
      imagePullSecrets for authentication, while allowing public registries
      without authentication (audit mode).
spec:
  validationFailureAction: audit  # Start with audit
  background: true
  rules:
    - name: validate-imagepullsecrets
      match:
        any:
        - resources:
            kinds:
            - Pod
            - Deployment
            - StatefulSet
            - DaemonSet
            - Job
            - CronJob
      exclude:
        resources:
          namespaces:
          - kube-system
          - kube-public
      validate:
        message: "Images from private registries must use imagePullSecrets"
        anyPattern:
        # Allow public registries without secrets
        - spec:
            containers:
            - image: "ghcr.io/cloudnative-pg/* | ghcr.io/codecentric/* | ghcr.io/external-secrets/* | ghcr.io/fluent/* | ghcr.io/fluxcd/* | ghcr.io/grafana/* | ghcr.io/kubeshop/* | ghcr.io/kyverno/* | ghcr.io/linkchecker/* | ghcr.io/metal-stack/* | ghcr.io/netbox-community/* | vaultwarden/* | hashicorp/* | goharbor/* | docker.gitea.com/* | docker.io/dragonflyoss/* | registry.k8s.io/* | xpkg.upbound.io/* | xpkg.crossplane.io/* | oci.external-secrets.io/*"
        # Require secrets for private registry
        - spec:
            containers:
            - image: "harbor.golder.lan/*"
            imagePullSecrets:
            - name: "?*"
