---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: rabbitmq
spec:
  image: bitnami/rabbitmq
  interval: 2h
  exclusionList:
    - 'sha256.*'
    - '.*test.*'
    - '.*debian.*'
    - '3.*'

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: rabbitmq
spec:
  imageRepositoryRef:
    name: rabbitmq
  policy:
    semver:
      range: '>=4.0.0'
