---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: rabbitmq-system
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: k8s-acme-operations
  namespace: rabbitmq-system
  annotations:
    kubernetes.io/description: "External Secrets SecretStore for RabbitMQ credentials from Vault"
spec:
  provider:
    vault:
      server: "https://vault.operations.acme.lan"
      path: k8s-acme-operations
      version: v2
      auth:
        jwt:
          path: jwt
          role: rabbitmq-system
          serviceAccountRef:
            name: external-secrets
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-role-rabbitmq-system
  namespace: rabbitmq-system
data:
  role: rabbitmq-system
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rabbitmq-admin-credentials
  namespace: rabbitmq-system
  annotations:
    kubernetes.io/description: "External Secret for RabbitMQ admin user credentials"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: k8s-acme-operations
  target:
    name: rabbitmq-admin-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: admin
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: rabbitmq-system/admin
