---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: rabbitmq-system
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: VAULT_SECRET_STORE_NAME
  namespace: rabbitmq-system
spec:
  provider:
    vault:
      server: "VAULT_SERVER_URL"
      path: VAULT_SECRET_PATH
      version: v2
      auth:
        jwt:
          path: jwt
          role: rabbitmq-system
          serviceAccountRef:
            name: external-secrets
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-role-rabbitmq-system
  namespace: rabbitmq-system
data:
  role: rabbitmq-system
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rabbitmq-admin-credentials
  namespace: rabbitmq-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: VAULT_SECRET_STORE_NAME
  target:
    name: rabbitmq-admin-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: admin
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: rabbitmq-system/admin
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: scratchmail-rabbitmq-credentials
  namespace: rabbitmq-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: VAULT_SECRET_STORE_NAME
  target:
    name: scratchmail-rabbitmq-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: scratchmail
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: rabbitmq-system/scratchmail
