---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rabbitmq-system
resources:
  - external-secrets.yaml
  - serviceaccounts.yaml
  - cluster-rbac.yaml
  - rabbitmq-cluster.yaml
  - webhook-certificate.yaml
  - topology
