---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  annotations:
    kubernetes.io/description: "RabbitMQ message broker cluster with MQTT and management interfaces"
spec:
  replicas: 1

  image: docker.io/bitnami/rabbitmq:4.1.2-debian-12-r0

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 1Gi

  persistence:
    storageClassName: csi-driver-lvm-linear
    storage: 5Gi

  rabbitmq:
    # Enable required plugins
    additionalPlugins:
      - rabbitmq_management
      - rabbitmq_mqtt
      - rabbitmq_prometheus

    # Additional config
    additionalConfig: |
      ## MQTT Configuration
      mqtt.allow_anonymous = false
      mqtt.vhost = mikrotik-system
      mqtt.exchange = amq.topic
      mqtt.tcp_listen_options.backlog = 128
      mqtt.tcp_listen_options.nodelay = true

      ## Default user (admin) - password will be from secret
      default_user = admin

      ## Prometheus metrics
      prometheus.tcp.port = 9419

    # Environment variables
    envConfig: |
      RABBITMQ_LOGS=-

  service:
    type: ClusterIP
    annotations:
      metallb.universe.tf/allow-shared-ip: rabbitmq

  # Override to expose additional ports
  override:
    service:
      spec:
        ports:
          - name: amqp
            protocol: TCP
            port: 5672
          - name: management
            protocol: TCP
            port: 15672
          - name: mqtt
            protocol: TCP
            port: 1883
          - name: mqtts
            protocol: TCP
            port: 8883

    statefulSet:
      spec:
        template:
          spec:
            containers:
              - name: rabbitmq
                ports:
                  - containerPort: 5672
                    name: amqp
                    protocol: TCP
                  - containerPort: 15672
                    name: management
                    protocol: TCP
                  - containerPort: 1883
                    name: mqtt
                    protocol: TCP
                  - containerPort: 8883
                    name: mqtts
                    protocol: TCP
