---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq
spec:
  releaseName: rabbitmq
  targetNamespace: rabbitmq
  chartRef:
    kind: OCIRepository
    name: bitnami-rabbitmq
    namespace: flux-system
  interval: 20m
