---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argocd
  annotations:
    kubernetes.io/description: "Declarative GitOps continuous delivery tool for Kubernetes applications"
spec:
  interval: 20m
  chart:
    spec:
      chart: argo-cd
      version: 7.3.11
      sourceRef:
        kind: HelmRepository
        name: argoproj
        namespace: flux-system
