---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: lvm-metrics-daily
  namespace: lvm-monitoring
spec:
  # Run every 4 hours
  schedule: "0 */4 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: lvm-metrics
            job-type: daily
        spec:
          serviceAccountName: lvm-monitor
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: container-repo-auth
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            fsGroup: 10001
            seccompProfile:
              type: RuntimeDefault
          containers:
          - name: monitor
            image: harbor.golder.lan/infrastructure/lvm-monitor:v1.0.0
            imagePullPolicy: IfNotPresent
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              runAsUser: 10001
              capabilities:
                drop:
                - ALL
              seccompProfile:
                type: RuntimeDefault
            command:
            - /bin/bash
            - -c
            - |
              # Export CA bundle if available
              if [ -f /etc/ssl/certs/golder-ca-certs/ca.crt ]; then
                export AWS_CA_BUNDLE=/etc/ssl/certs/golder-ca-certs/ca.crt
                export CURL_CA_BUNDLE=/etc/ssl/certs/golder-ca-certs/ca.crt
                export SSL_CERT_FILE=/etc/ssl/certs/golder-ca-certs/ca.crt
              fi
              
              # Run the monitoring script
              /opt/scripts/monitor-lvm.sh
              
              # Run the Python metrics exporter
              python3 /opt/scripts/lvm-metrics-exporter.py
            volumeMounts:
            - name: scripts
              mountPath: /opt/scripts
            - name: python-script
              mountPath: /opt/scripts/lvm-metrics-exporter.py
              subPath: lvm-metrics-exporter.py
            - name: ca-bundle
              mountPath: /etc/ssl/certs/golder-ca-certs
              readOnly: true
            env:
            - name: CLUSTER_NAME
              value: "kubernetes"  # Override in cluster kustomization
            - name: PROMETHEUS_PUSH_GATEWAY
              value: "http://prometheus-pushgateway.monitoring.svc.cluster.local:9091"
            - name: LOG_LEVEL
              value: "INFO"
            - name: RUN_INTERVAL_SECONDS
              value: "0"
            - name: KUBERNETES_CONTEXT
              value: "kubernetes"  # Override in cluster kustomization
            resources:
              requests:
                memory: "512Mi"
                cpu: "100m"
              limits:
                memory: "2Gi"
                cpu: "500m"
            envFrom:
            - secretRef:
                name: push-gateway-auth
                optional: true
            - secretRef:
                name: lvm-reports-minio
                optional: true
            - secretRef:
                name: lvm-monitor-webhook
                optional: true
          volumes:
          - name: scripts
            configMap:
              name: lvm-monitor-scripts
              defaultMode: 0755
          - name: python-script
            configMap:
              name: lvm-metrics-exporter-script
              defaultMode: 0755
          - name: ca-bundle
            secret:
              secretName: golder-ca-certs
              optional: true

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: lvm-monitor-hourly
  namespace: lvm-monitoring
spec:
  # Run every hour for critical checks
  schedule: "15 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: lvm-monitor
            job-type: hourly-check
        spec:
          serviceAccountName: lvm-monitor
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: container-repo-auth
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            fsGroup: 10001
            seccompProfile:
              type: RuntimeDefault
          containers:
          - name: monitor
            image: harbor.golder.lan/infrastructure/lvm-monitor:v1.0.0
            imagePullPolicy: IfNotPresent
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              runAsUser: 10001
              capabilities:
                drop:
                - ALL
              seccompProfile:
                type: RuntimeDefault
            command:
            - /bin/bash
            - -c
            - |
              # Export CA bundle if available
              if [ -f /etc/ssl/certs/golder-ca-certs/ca.crt ]; then
                export AWS_CA_BUNDLE=/etc/ssl/certs/golder-ca-certs/ca.crt
                export CURL_CA_BUNDLE=/etc/ssl/certs/golder-ca-certs/ca.crt
                export SSL_CERT_FILE=/etc/ssl/certs/golder-ca-certs/ca.crt
              fi
              
              # Run the monitoring script
              /opt/scripts/monitor-lvm.sh
            volumeMounts:
            - name: scripts
              mountPath: /opt/scripts
            - name: ca-bundle
              mountPath: /etc/ssl/certs/golder-ca-certs
              readOnly: true
            resources:
              requests:
                memory: "256Mi"
                cpu: "100m"
              limits:
                memory: "1Gi"
                cpu: "500m"
            envFrom:
            - secretRef:
                name: lvm-reports-minio
                optional: true
            - secretRef:
                name: lvm-monitor-webhook
                optional: true
            env:
            - name: KUBERNETES_CONTEXT
              value: "kubernetes"  # Override in cluster kustomization
          volumes:
          - name: scripts
            configMap:
              name: lvm-monitor-scripts
              defaultMode: 0755
          - name: ca-bundle
            secret:
              secretName: golder-ca-certs
              optional: true