---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lvm-monitoring
resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - cronjob.yaml
  - deployment.yaml
  - prometheus-rules.yaml
  # - daemonset.yaml  # Optional: Uncomment for node-level LVM monitoring

images:
  - name: PRIVATE_REGISTRY/library/lvm-metrics-exporter
    newTag: latest

# These are meant to be overridden in cluster-specific overlays
configMapGenerator:
  - name: lvm-monitor-config
    behavior: create
    literals:
      - CLUSTER_NAME=kubernetes
  - name: lvm-metrics-exporter-script
    files:
      - lvm-metrics-exporter.py