---
apiVersion: v1
kind: Namespace
metadata:
  name: lvm-monitoring
  labels:
    toolkit.fluxcd.io/tenant: platform
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
  annotations:
    kubernetes.io/description: "LVM storage monitoring and metrics collection"