---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/name: kobold
    app.kubernetes.io/version: v0.3.3
  name: kobold-api
spec:
  ports:
  - name: http
    port: 80
    targetPort: api
  selector:
    app.kubernetes.io/name: kobold
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/name: kobold
    app.kubernetes.io/version: v0.3.3
  name: kobold-webhook
spec:
  ports:
  - name: http
    port: 80
    targetPort: webhook
  selector:
    app.kubernetes.io/name: kobold
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: kobold
    app.kubernetes.io/version: v0.3.3
  name: kobold
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kobold
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kobold
    spec:
      containers:
      - args:
        - -confd=/etc/kobold/conf.d
        - -db=/tmp/kobold.db
        envFrom:
        - secretRef:
            name: kobold-env
            optional: true
        image: docker.io/bluebrown/kobold:v0.3.3 # {"$imagepolicy": "kobold:kobold"}
        name: kobold
        ports:
        - containerPort: 8080
          name: webhook
        - containerPort: 9090
          name: api
        resources:
          limits:
            cpu: 2000m
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: data
        - mountPath: /etc/kobold/conf.d
          name: confd
          readOnly: true
        - mountPath: /etc/kobold/.ssh
          name: ssh
          readOnly: true
        - mountPath: /etc/kobold/.gitconfig
          name: gitconfig
          readOnly: true
          subPath: .gitconfig
        - mountPath: /etc/kobold/.git-credentials
          name: gitcreds
          readOnly: true
          subPath: .git-credentials
      securityContext:
        fsGroup: 65532
        runAsNonRoot: true
      volumes:
      - emptyDir: {}
        name: data
      - configMap:
          name: kobold-confd
        name: confd
      - name: ssh
        secret:
          secretName: kobold-ssh
      - configMap:
          name: kobold-gitconfig
        name: gitconfig
      - name: gitcreds
        secret:
          secretName: kobold-gitcreds
