---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: external-dns
spec:
  image: registry.k8s.io/external-dns/external-dns
  interval: 20m

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: external-dns
spec:
  imageRepositoryRef:
    name: external-dns
  policy:
    semver:
      range: '>=0.14.0'