---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  interval: 20m
  chart:
    spec:
      chart: external-dns
      version: 1.14.5
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  values:
    triggerLoopOnEvent: true
    interval: 5m
    logFormat: json
    # Provider-specific configuration should be added via cluster-specific patches
