---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudnative-pg
  annotations:
    kubernetes.io/description: "CloudNativePG operator charts for PostgreSQL cluster management in Kubernetes"
spec:
  interval: 60m
  url: https://cloudnative-pg.github.io/charts
