---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  annotations:
    kubernetes.io/description: "External DNS Helm charts for automatic DNS record management from Kubernetes resources"
spec:
  interval: 60m
  url: https://kubernetes-sigs.github.io/external-dns
