---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  annotations:
    kubernetes.io/description: "External Secrets Operator charts for syncing secrets from external secret management systems"
spec:
  interval: 60m
  url: https://charts.external-secrets.io
