---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kyverno
  annotations:
    kubernetes.io/description: "Kyverno policy engine charts for Kubernetes policy management and governance"
spec:
  interval: 60m
  url: https://kyverno.github.io/kyverno/
