---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metalstack
  annotations:
    kubernetes.io/description: "Metal Stack charts for bare metal Kubernetes infrastructure management"
spec:
  interval: 60m
  url: https://helm.metal-stack.io
