---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rabbitmq-cluster-operator-manager
  namespace: rabbitmq-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: rabbitmq-cluster-operator
    namespace: rabbitmq-system
  path: "./config/manager"
  prune: true
