---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: rabbitmq-messaging-topology-operator
  namespace: rabbitmq-system
spec:
  interval: 10m
  url: https://github.com/rabbitmq/messaging-topology-operator
  ref:
    tag: v1.15.0
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rabbitmq-messaging-topology-operator
  namespace: rabbitmq-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: rabbitmq-messaging-topology-operator
    namespace: rabbitmq-system
  path: "./config/crd"
  prune: true
