---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  annotations:
    kubernetes.io/description: "High-performance S3-compatible object storage server"
spec:
  interval: 18m
  chart:
    spec:
      chart: minio
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  values:
    mode: standalone  # not 'distributed'
    drivesPerNode: 1
    replicas: 8
    pools: 2

    tls:
      enabled: true
      certSecret: minio-tls
      publicCrt: tls.crt
      privateKey: tls.key

    resources:
      limits:
        memory: 4Gi
      requests:
        memory: 2Gi