---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argo-events
spec:
  interval: 20m
  chart:
    spec:
      chart: argo-events
      version: 2.4.9
      sourceRef:
        kind: HelmRepository
        name: argoproj
        namespace: flux-system