---
apiVersion: v1
kind: Service
metadata:
  name: ipfs-peering-service
spec:
  selector:
    app: ipfs-daemon
  ports:
  - protocol: TCP
    port: 4001
    targetPort: 4001

---
apiVersion: v1
kind: Service
metadata:
  name: ipfs-api-service
spec:
  selector:
    app: ipfs-daemon
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001

---
apiVersion: v1
kind: Service
metadata:
  name: ipfs-web
spec:
  selector:
    app: ipfs-daemon
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
