---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 20m
  chart:
    spec:
      chart: cert-manager
      version: v1.16.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  values:
    installCRDs: true
    global:
      podSecurityPolicy:
        enabled: false
        useAppArmor: false