---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  annotations:
    kubernetes.io/description: "cert-manager automates the management and issuance of TLS certificates from various certificate authorities"
spec:
  interval: 20m
  timeout: 10m
  chart:
    spec:
      chart: cert-manager
      version: v1.16.0
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
  values:
    installCRDs: true
    global:
      podSecurityPolicy:
        enabled: false
        useAppArmor: false
