---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-collector
  annotations:
    kubernetes.io/description: "OpenTelemetry Collector for receiving, processing and exporting telemetry data"
spec:
  interval: 18m
  chart:
    spec:
      chart: opentelemetry-collector
      version: 0.101.1
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
        namespace: flux-system
  values: {}
