apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vaultwarden-secrets
  namespace: vaultwarden
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-secretstore
    kind: SecretStore
  target:
    name: vaultwarden-secrets
    creationPolicy: Owner
  data:
  - secretKey: database-url
    remoteRef:
      key: vaultwarden
      property: database-url
  - secretKey: admin-token
    remoteRef:
      key: vaultwarden
      property: admin-token
  - secretKey: metrics-token
    remoteRef:
      key: vaultwarden
      property: metrics-token