---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  annotations:
    kubernetes.io/description: "Self-hosted password manager compatible with Bitwarden clients"
spec:
  interval: 20m
  chart:
    spec:
      chart: vaultwarden
      version: 1.2.5
      sourceRef:
        kind: HelmRepository
        name: gissilabs
        namespace: flux-system
