apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: signoz
  namespace: observability
spec:
  interval: 30m
  timeout: 30m
  chart:
    spec:
      chart: signoz
      version: "0.85.1"
      sourceRef:
        kind: HelmRepository
        name: signoz
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    global:
      storageClass: csi-driver-lvm-linear
      cloud: other
      # imagePullSecrets configured per cluster

    clickhouse:
      enabled: true
      persistence:
        enabled: true
        size: 10Gi
        storageClass: csi-driver-lvm-linear
      resources:
        limits:
          memory: "2Gi"
          cpu: "1000m"
        requests:
          memory: "1Gi"
          cpu: "500m"

    queryService:
      persistence:
        enabled: true
        size: 2Gi
        storageClass: csi-driver-lvm-linear
      resources:
        limits:
          memory: "1Gi"
          cpu: "500m"
        requests:
          memory: "512Mi"
          cpu: "250m"

    frontend:
      ingress:
        enabled: false  # Configured per cluster
      resources:
        limits:
          memory: "512Mi"
          cpu: "250m"
        requests:
          memory: "256Mi"
          cpu: "100m"

    otelCollector:
      enabled: true
      ingress:
        enabled: false
      resources:
        limits:
          memory: "512Mi"
          cpu: "250m"
        requests:
          memory: "256Mi"
          cpu: "100m"

    zookeeper:
      persistence:
        enabled: true
        storageClass: csi-driver-lvm-linear
        size: 5Gi
      resources:
        limits:
          memory: "256Mi"
          cpu: "100m"
        requests:
          memory: "128Mi"
          cpu: "50m"
