---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 20m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 72.1.0
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: flux-system