---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-upstream
  namespace: flux-system
spec:
  interval: 30m
  ref:
    tag: v2.6.4
  url: https://github.com/fluxcd/flux2
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-components
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/install
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-upstream
  targetNamespace: flux-system
  wait: true
  # Exclude source-controller from flux-components since clusters provide their own custom version
  patches:
  - patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: source-controller
        namespace: flux-system
    target:
      kind: Deployment
      name: source-controller
      namespace: flux-system
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: source-controller
        namespace: flux-system
    target:
      kind: Service
      name: source-controller
      namespace: flux-system
