---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: loki
spec:
  image: grafana/loki
  interval: 20m

---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: loki
spec:
  imageRepositoryRef:
    name: loki
  policy:
    semver:
      range: '>=3.1.0'
