---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  annotations:
    kubernetes.io/description: "Loki is a horizontally-scalable, highly-available log aggregation system inspired by Prometheus"
spec:
  serviceName: loki
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:3.1.0 # {"$imagepolicy": "loki:loki"}
          ports:
            - containerPort: 3100
          volumeMounts:
            - name: config
              mountPath: /etc/loki/local-config.yaml
              subPath: config.yaml
            - name: config
              mountPath: /etc/loki/rules/rules.yaml
              subPath: rules.yaml
            - name: data
              mountPath: /loki
      volumes:
        - name: config
          configMap:
            name: loki
        - name: data
          persistentVolumeClaim:
            claimName: logs
