---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  annotations:
    kubernetes.io/description: "Enterprise-class container registry with security scanning and policy management"
spec:
  interval: 20m
  chart:
    spec:
      chart: harbor
      version: 1.17.1
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: harbor-admin
      valuesKey: HARBOR_ADMIN_PASSWORD
      targetPath: harborAdminPassword
