---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  annotations:
    kubernetes.io/description: "Open source identity and access management solution with SSO support"
spec:
  interval: 20m
  chart:
    spec:
      chart: keycloakx
      version: 7.0.1
      sourceRef:
        kind: HelmRepository
        name: codecentric
        namespace: flux-system
  values:
    # Base configuration - override in cluster-specific configurations
    replicas: 1
    # Additional values should be provided by cluster-specific patches
