---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: flux-golder
  namespace: flux-system
spec:
  interval: 18m
  sourceRef:
    kind: GitRepository
    name: flux-golder
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: flux-image-automation@golder.org
        name: Flux2
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: master
  update:
    path: ./clusters/PLACEHOLDER
    strategy: Setters
