---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: FLUX_REPO_NAME
  namespace: flux-system
spec:
  type: github
  events:
    - "ping"
    - "push"
  secretRef:
    name: webhook-token
  resources:
    - kind: GitRepository
      name: FLUX_REPO_NAME
