# Simplified workflow that works without pre-configured Pages
name: Build Hugo Documentation

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.147.9
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb          
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Initialize submodules
        run: git submodule update --init --recursive
      - name: Debug - Check Hugo and theme
        run: |
          hugo version
          ls -la docs/themes/
          ls -la docs/themes/hugo-book/ || echo "Theme directory not found"
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          cd docs
          hugo --gc --minify --baseURL "https://rossigee.github.io/flux-shared-platform/"
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: hugo-site
          path: docs/public/
          retention-days: 30
      - name: Build Status
        run: |
          echo "✅ Hugo site built successfully!"
          echo "📁 Built files:"
          ls -la docs/public/
          echo ""
          echo "🚀 To enable GitHub Pages:"
          echo "1. Go to Settings → Pages"
          echo "2. Set Source to 'GitHub Actions'"
          echo "3. Site will be live at: https://rossigee.github.io/flux-shared-platform"